---
ocp4_workload_rhads_customisation_argocd_version: "v3.1.5"
ocp4_workload_rhads_customisation_namespace: tssc-keycloak
ocp4_workload_rhads_customisation_new_size: 10Gi
ocp4_workload_rhads_customisation_cluster_app_domain: "cluster-{{ guid }}.dynamic.redhatworkshops.io"
ocp4_workload_rhads_customisation_ocp_console_url: "https://console-openshift-console.apps.{{ ocp4_workload_rhads_customisation_cluster_app_domain }}"
ocp4_workload_rhads_customisation_logout_redirect_url: >-
  https://sso.apps.{{ ocp4_workload_rhads_customisation_cluster_app_domain }}/realms/trusted-artifact-signer/protocol/openid-connect/logout?client_id=ocp4_workload_advanced_developer_suite_openshift_keycloak_client_id&post_logout_redirect_uri={{ ocp4_workload_rhads_customisation_ocp_console_url }}
ocp4_workload_rhads_customisation_argo_namespace: tssc-gitops
ocp4_workload_rhads_customisation_argo_username: admin
ocp4_workload_rhads_customisation_cluster_context: admin
ocp4_workload_rhads_customisation_kubeconfig_path: "{{ ansible_env.HOME }}/.kube/config"
###########################################################
ocp4_workload_rhads_customisation_rhdh_dynamic_template: "dynamic-plugins.yaml.j2"
ocp4_workload_rhads_customisation_rhdh_namespace: "tssc-dh"
ocp4_workload_rhads_customisation_rhdh_cm_name: "tssc-developer-hub-dynamic-plugins"
